version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/build-image
    steps:
       - setup_remote_docker
      - run:
          name: Start all services declared in docker-compose.yml
          command: |
            docker-compose up -d
      - run: npm run test:unit